function [J1, J2] = compute_objectives_split( ...
    src, obj, h_story_m, tail_sec, ...
    t_rawX,t_rawY,a_rawX,a_rawY,t_sclX,t_sclY,a_sclX,a_sclY, ...
    t5x_raw,t95x_raw,t5y_raw,t95y_raw,t5x_scl,t95x_scl,t5y_scl,t95y_scl, ...
    M,Cstr,K,n,geom,sh,orf,hyd,therm,num,cfg, design_set, x_ga)

% Compute objective components separately:
%   J1 - IDR zarf oranı CVaR
%   J2 - mutlak ivme (RMS+p95) zarf oranı CVaR
    [J1, ~] = compute_J1_IDR_over_records( ...
        src, obj, h_story_m, tail_sec, ...
        t_rawX,t_rawY,a_rawX,a_rawY,t_sclX,t_sclY,a_sclX,a_sclY, ...
        t5x_raw,t95x_raw,t5y_raw,t95y_raw,t5x_scl,t95x_scl,t5y_scl,t95y_scl, ...
        M,Cstr,K,n,geom,sh,orf,hyd,therm,num,cfg, design_set, x_ga);

    [J2, ~] = compute_J2_ACC_over_records( ...
        src, obj, h_story_m, tail_sec, ...
        t_rawX,t_rawY,a_rawX,a_rawY,t_sclX,t_sclY,a_sclX,a_sclY, ...
        t5x_raw,t95x_raw,t5y_raw,t95y_raw,t5x_scl,t95x_scl,t5y_scl,t95y_scl, ...
        M,Cstr,K,n,geom,sh,orf,hyd,therm,num,cfg, design_set, x_ga);
end
